### PR TITLE
Update poster image and add orientation session link.

### PR DESCRIPTION
**Pull request by Ashrockzzz2003**
- [x] Updated poster image.
- [x] Orientation Session link added.
- [x] Update maintainer list
- [x] Add missing projects
- [ ] Add description and tech icons for each project along with hyperlink

### CODE REVIEW

**Review by IAmRiteshKoushik — CHANGES_REQUESTED** [review]
Can you populate the projects section with the 2-line description, hyperlink the projects to their respective repository in the heading itself and use the techstack icons in your profile to add the tech stack for each project ?

@Ashrockzzz2003

**Comment by IAmRiteshKoushik** [comment]
The maintainers list needs to be updated too.

**Comment by IAmRiteshKoushik** [comment]
Projects by @SaranDharshanSP and @VishalTheHuman have it been added yet. Could we have those too please @Ashrockzzz2003 ?

**Comment by Ashrockzzz2003** [comment]
Details of repo and tech stack will add it through another PR. These updates are quite important to be there.

**Review by IAmRiteshKoushik — APPROVED** [review]
LGTM

**Pull request merged**
